# Generated by Django 5.0.3 on 2024-08-07 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tshit', 'tshit'), ('sneaker', 'sneaker'), ('pants', 'pants')], max_length=40)),
                ('name', models.CharField(max_length=50)),
                ('tamanho', models.FloatField()),
                ('image', models.ImageField(upload_to='snkrs-img/')),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=400)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
            ],
        ),
    ]
