# Generated by Django 5.1 on 2024-08-17 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='ctg-img')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('used', 'Used'), ('new', 'New')], default='new', max_length=40, verbose_name='Product Status')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity in Stock')),
                ('size', models.FloatField(default=1, verbose_name='Size')),
                ('image', models.ImageField(upload_to='snkrs-img/', verbose_name='Product Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.CharField(max_length=400, verbose_name='Description')),
                ('sport', models.CharField(choices=[('soccer', 'Soccer'), ('basketball', 'Basketball'), ('running', 'Running'), ('volleyball', 'Volleyball'), ('skakeboarding', 'Skateboarding'), ('tennis', 'Tennis'), ('golf', 'Golf'), ('baseball', 'Baseball'), ('football', 'Football')], default='soccer', max_length=20, verbose_name='Sport')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brand.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
