# Generated by Django 5.1 on 2024-08-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_seller_alter_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('used', 'Used'), ('new', 'New')], default='new', max_length=40, verbose_name='Product Status'),
        ),
    ]
