# Generated by Django 5.1 on 2024-08-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='sport',
            field=models.CharField(choices=[('soccer', 'Soccer'), ('basketball', 'Basketball'), ('running', 'Running'), ('volleyball', 'Volleyball'), ('skakeboarding', 'Skateboarding')], default='soccer', max_length=20, verbose_name='Sport'),
        ),
    ]
