# Generated by Django 5.1 on 2024-08-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_type_product_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='ctg-img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sport',
            field=models.CharField(choices=[('soccer', 'Soccer'), ('basketball', 'Basketball'), ('running', 'Running'), ('volleyball', 'Volleyball'), ('skakeboarding', 'Skateboarding'), ('tennis', 'Tennis'), ('golf', 'Golf'), ('baseball', 'Baseball'), ('football', 'Football')], default='soccer', max_length=20, verbose_name='Sport'),
        ),
    ]
