# Generated by Django 5.1 on 2024-08-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_username_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='about'),
        ),
    ]
