# Generated by Django 5.1 on 2024-08-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
